[package]
name = "sketch"
version = "0.0.1"
authors = ["Caleb Daniels <CJordanDaniels@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

description = "Vulkan rendering system"
license = "GPL-3.0-or-later"

[dependencies]
ash = "0.29.0"
winit = "0.20.0"
log = "0.4.8"
wind = { path = "../wind", version = "0.0.1" }